apiVersion: v1
data:
  password: Qk9UQHdlYjEyMw==
  port: NDY1
  tls: VHJ1ZQ==
  url: c210cC5leG1haWwucXEuY29t
  user: d2ViYm90QHpkbnMuY24=
kind: Secret
metadata:
  name: zddiweb-email
  namespace: devops
type: Opaque

---

apiVersion: v1
stringData:
  access_token: 6066c121f9d18f79c157dd05a750bbc299be7ae731170734542bc7027e4e4dbe
  secret: SEC9e17ca70431c2b6735fc01bf4bccd5fc6ba9163b74127975d78d4f84e1f5adb7
kind: Secret
metadata:
  name: my-dingding
  namespace: devops
type: Opaque
