apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-listener-interceptor
  namespace: devops
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: push-event
      interceptors:
        - gitlab:
            eventTypes:
              - Push Hook
      bindings:
        - ref: gitlab-push-event-bindings
      template:
        name: zddiv3-web-push-pipeline
    - name: pipeline-event
      interceptors:
        - gitlab:
            eventTypes:
              - Pipeline Hook
      bindings:
        - ref: gitlab-pipeline-event-bindings
      template:
        name: zddiv3-web-pipeline-pipeline

