apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-zcloud-web-listener-interceptor
  namespace: devops
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: push-event
      interceptors:
        - gitlab:
            eventTypes:
              - Push Hook
      bindings:
        - ref: gitlab-push-event-bindings
      template:
        name: zcloud-web-push
    - name: merge-request-event
      interceptors:
        - gitlab:
            eventTypes:
              - Merge Request Hook
      bindings:
        - ref: gitlab-merge-request-event-bindings
      template:
        name: zcloud-web-merge-requst

