apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yarn-cache
  namespace: devops
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
