---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail-after-push
  namespace: devops
spec:
  params:
    - name: server
      type: string
      description: secret name for SMTP server information (url, port, password)
    - name: subject
      type: string
      description: plain text email subject
      default: 'Title'
    - name: sender
      type: string
      description: Email from section
      default: "webbot@zdns.cn"
    - name: recipients
      type: string
      description: recipient email addresses (space delimited list)
      default: "zddiweb@zdns.cn"
    - name: lintResult
      type: string
    - name: buildResult
      type: string
    - name: pushResult
      type: string
    - name: pushOutput
      type: string
  steps:
  - name: send
    workingDir: $(workspaces.repo.path)
    image: python:3.8-alpine
    script: |-
      #!/usr/bin/env python3
      import smtplib, ssl, os
      port = os.getenv('PORT')
      smtp_server = os.getenv('SERVER')
      sender_email = "$(params.sender)"
      receiver_emails = "$(params.recipients)"
      user = os.getenv('USER')
      password = os.getenv('PASSWORD')
      tls = os.getenv('TLS')
      lintFile = open('lint-log.txt', 'r')
      lintText = lintFile.read()
      buildFile = open('build-log.txt', 'r')
      buildText = buildFile.read()
      pushFile = open('push.log', 'r')
      pushText = pushFile.read()
      message = f"""\
      Subject: $(params.subject)
      To: {receiver_emails}
      From: {sender_email}
      Bcc: {sender_email}

      ===

      $(params.subject)

      ===
      
      Lint Result <$(params.lintResult)>: 
      {lintText}

      ===

      Build Result <$(params.buildResult)>:
      {buildText}

      ===

      Push Package: <$(params.pushResult)>:
      {pushText}

      ==="""
      message = message.encode('utf-8').strip()
      print(message)
      if tls == 'True':
          context = ssl.create_default_context()
          server = smtplib.SMTP_SSL(smtp_server, port, context=context)
      else:
          server = smtplib.SMTP(smtp_server, port)
      if password != '':
          server.login(user, password)
      for receiver in receiver_emails.split(' '):
          server.sendmail(sender_email, receiver, message)
      server.quit()
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: $(params.server)
          key: user
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: $(params.server)
          key: password
    - name: TLS
      valueFrom:
        secretKeyRef:
          name: $(params.server)
          key: tls
    - name: SERVER
      valueFrom:
        secretKeyRef:
          name: $(params.server)
          key: url
    - name: PORT
      valueFrom:
        secretKeyRef:
          name: $(params.server)
          key: port
  workspaces:
    - name: repo
---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yarn-install
  namespace: devops
spec:
  workspaces:
    - name: repo
  steps:
    - name: install
      workingDir: $(workspaces.repo.path)
      image: node:12-alpine
      script: |
        #!/bin/sh
        time_start=$(date +%s)
        REPO=$(workspaces.repo.path)
        echo "REPO: ${REPO}"
        yarn --offline || rm yarn.lock && yarn
        RESULT=$?
        time_end=$(($(date +%s) - $time_start))
        echo "[Install complete] in ${time_end} seconds"
        test "$RESULT" != 0 || exit $RESULT
      volumeMounts:
        - name: yarnrc
          mountPath: /tekton/home/.yarnrc
          subPath: config
        - name: yarn-cache
          mountPath: /yarn-cache
  volumes:
    - name: yarnrc
      configMap:
        name: yarnrc
    - name: yarn-cache
      persistentVolumeClaim:
        claimName: yarn-cache



---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yarn-run
  namespace: devops
spec:
  params:
    - name: cmd
      type: string
      default: lint
  results:
    - name: output
      description: task run output
    - name: result
      description: task run result
  steps:
    - name: run
      workingDir: $(workspaces.repo.path)
      image: node:12-alpine
      script: |
        #!/bin/sh
        REPO=$(workspaces.repo.path)
        yarn run $(params.cmd) | tee $(params.cmd)-log.txt
        echo $? | tee $(results.result.path)
      volumeMounts:
        - name: yarnrc
          mountPath: /tekton/home/.yarnrc
          subPath: config
        - name: yarn-cache
          mountPath: /yarn-cache
  volumes:
    - name: yarnrc
      configMap:
        name: yarnrc
    - name: yarn-cache
      persistentVolumeClaim:
        claimName: yarn-cache
  workspaces:
    - name: repo

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-build
  namespace: devops
spec:
  results:
    - name: output
      description: task run output
    - name: result
      description: task run result
  params:
    - name: user_name
      description: user display name
    - name: revision
      description: git revision
    - name: ref
      description: git reference
  steps:
    - name: push
      workingDir: $(workspaces.repo.path)
      image: gsmlg/curl-make-git:zddi-web
      script: |
        #!/bin/sh
        if test -x bin/hash_linux
        then
          echo "New version, auto save package" | tee -a $(results.output.path) | tee -a push.log
          make tar | tee -a $(results.output.path) | tee -a push.log
          branch=`echo $(params.ref) | sed 's;/;_;g'`
          make ciupload USERNAME=$(params.user_name) COMMIT=$(params.revision) BRANCH=${branch} | tee -a $(results.output.path) | tee -a push.log
        else
          echo "Old version, need to upload manually" | tee -a $(results.output.path) | tee -a push.log
        fi
        echo $? | tee $(results.result.path)
  workspaces:
    - name: repo

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zddi-web-ci-pipeline
  namespace: devops
spec:
  workspaces:
    - name: repo
  params:
    - name: project_name
      type: string
      description: project name
      default: zddiv3-web
    - name: repository_url
      type: string
      default: git@git.zdns.cn:zdns/zddiv3-web.git
    - name: revision
      type: string
      default: master
    - name: ref
      type: string
      default: refs/origin/master
    - name: user_name
      type: string
      description: gitlab user display name
      default: 'bot'
    - name: user_username
      type: string
      description: git username
      default: webbot
    - name: user_email
      type: string
      description: gitlab user email
      default: zddiweb@zdns.cn
  tasks:
    - name: clone
      taskRef: 
        name: git-clone
      workspaces:
        - name: output
          workspace: repo
      params:
        - name: url
          value: $(params.repository_url)
        - name: revision
          value: $(params.revision)
        - name: submodules
          value: "false"
    - name: install
      taskRef:
        name: yarn-install
      runAfter:
        - clone
      workspaces:
        - name: repo
          workspace: repo
    - name: lint
      taskRef:
        name: yarn-run
      runAfter:
        - install
      params:
        - name: cmd
          value: lint
      workspaces:
        - name: repo
          workspace: repo
    - name: build
      taskRef:
        name: yarn-run
      runAfter:
        - install
      params:
        - name: cmd
          value: build
      workspaces:
        - name: repo
          workspace: repo
    - name: push
      taskRef:
        name: push-build
      runAfter:
        - build
      workspaces:
        - name: repo
          workspace: repo
      params:
        - name: user_name
          value: $(params.user_name)
        - name: revision
          value: $(params.revision)
        - name: ref
          value: $(params.ref)
    - name: report
      taskRef:
        name: sendmail-after-push
      runAfter:
        - lint
        - build
        - push
      workspaces:
        - name: repo
          workspace: repo
      params:
        - name: lintResult
          value: $(tasks.lint.results.result)
        - name: buildResult
          value: $(tasks.build.results.result)
        - name: pushOutput
          value: $(tasks.push.results.output)
        - name: pushResult
          value: $(tasks.push.results.result)
        - name: sender
          value: WebBot<webbot@zdns.cn>
        - name: recipients
          value: $(params.user_email)
        - name: server
          value: zddiweb-email
        - name: subject
          value: $(params.user_name)（$(params.user_username)）提交请求<$(params.ref)>($(params.revision)) CI 运行结果

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: zddiv3-web-push-pipeline
  namespace: devops
spec:
  params:
  - name: project_name
    description: Project Name
    default: zddiv3-web
  - name: revision
    description: The git revision
    default: master
  - name: repository_url
    description: The git repository url
    default: git@git.zdns.cn:zdns/zddiv3-web.git
  - name: user_name
    description: The gitlab user display name
    default: ''
  - name: user_username
    default: ''
  - name: user_email
    description: The gitlab user email
    default: ''
  - name: ref
    description: The git commit ref
    default: ''
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: web-push-pipeline-run-
        namespace: devops
      spec:
          serviceAccountName: pipeline-run-service
          pipelineRef:
            name: zddi-web-ci-pipeline
          timeout: "2h0m0s"
          workspaces:
            - name: repo
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs
                  accessModes:
                    - ReadWriteMany
                  resources:
                    requests:
                      storage: 1Gi
          params:
            - name: project_name
              value: $(params.project_name)
            - name: repository_url
              value: $(params.repository_url)
            - name: revision
              value: $(params.revision)
            - name: ref
              value: $(params.ref)
            - name: user_name
              value: $(params.user_name)
            - name: user_username
              value: $(params.user_username)
            - name: user_email
              value: $(params.user_email)

